version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - my-network

  inventory-service:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DATABASE: inventory
      MONGO_USERNAME: wualter
      MONGO_PASSWORD: "123456"
    networks:
      - my-network

networks:
  my-network:
