server:
  port: 9092

spring:
  data:
    mongodb:
      host: mongodbreactive
      port: 27017
      database: inventory
      username: admin
      password: mongo123
      authentication-database: inventory

#spring:
#  data:
#    mongodb:
#      host: ${DB_MONGO_HOST}
#      port: ${DB_MONGO_PORT}
#      database: ${DB_MONGO_DATABASE}
#      username: ${DB_MONGO_USERNAME}
#      password: ${DB_MONGO_PASWORD}
#      authentication-database: ${DB_MONGO_AUTH_DB}

#spring:
#  data:
#    mongodb:
#      uri: mongodb://admin:mongo123@localhost:27017/inventory?authSource=inventory
