server:
  port: 9092

#spring:
#  data:
#    mongodb:
#      host: ${MONGO_HOST}
#      port: ${MONGO_PORT}
#      database: ${MONGO_DATABASE}
#      username: ${MONGO_USERNAME}
#      password: ${MONGO_PASWORD}

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: inventory
      #      authentication-database: admin
      username: wualter
      password: "123456"

#db.createUser({user: "admin",pwd:"123456",roles:["root"]})

#spring:
#  data:
#    mongodb:
#      uri: mongodb://localhost:27017/inventory


#db.createUser({
#user: "wualter",
#pwd: "123456",
#roles: [
#  { role: "readWrite", db: "inventory" },
#  { role: "dbAdmin", db: "inventory" }
#]
#})